[package]
name = "robot-demos"
version = "0.1.0"
edition = "2021"

# Default binary (src/main.rs) - this is automatic
# Additional binary targets can be specified here:
[[bin]]
name = "base-ez-control"
path = "example/base-ez-control.rs"

[[bin]]
name = "base-ez-control-websocket"
path = "example/base-ez-control-websocket.rs"

[[bin]]
name = "linear-lift-move-websocket"
path = "example/linear-lift-move-websocket.rs"

[[bin]]
name = "read-ts"
path = "example/read-ts.rs"

[dependencies]
futures-channel = "0.3.31"
futures-util = "0.3.31"
tokio = { version = "1.41.0", features = ["full"] }
prost = "0.12"
env_logger = "0.11.5"
clap = { version = "4.5.20", features = ["derive"] }
anyhow = "1.0.91"
serde = { version = "1.0.213", features = ["derive"] }
log = { version = "0.4.22", features = ["std"] }
tokio-util = "0.7.12"
libc = "0.2"
tokio-tungstenite = "0.27.0"
tungstenite = "0.27.0"
lazy_static = "1.4.0"
kcp-bindings = {version = "1.0.1", features = ["hexfellow"]}
# kcp-bindings = { path = "../kcp-bindings", features = ["hexfellow"] }

[build-dependencies]
prost-build = { version = "0.12.4" }
